### ISSUE TITLE
Exporter fails with “context deadline exceeded” when retrieving starred repos

### ISSUE THREAD

**Issue by jk** [hasansino/github2karakeep#1]
When I start the container with a proper configuration, I get the following error

```
Failed to execute exporter: failed to retrieve starred repos: failed to retrieve starred: context deadline exceeded
```

Config in `docker-compose.yml`:
```yaml
services:
  github2karakeep:
    image: ghcr.io/hasansino/github2karakeep:latest
    environment:
      - TIMEOUT=10s
      - GH_USERNAME=jk
      - GH_TOKEN=github_pat_[redacted]
      - GH_PER_PAGE=10
      - KK_HOST=https://[redacted]
      - KK_TOKEN=[redacted]
      - KK_LIST=github2karakeep
      - UPDATE_INTERVAL=6h
      - EXPORT_LIMIT=10
      - DEFAULT_TAG=github
```
